# Site settings
title: My Data Science Portfolio
description: A collection of my data science projects
baseurl: "" # Change if using a subfolder
url: "https://cherzs.github.io" # Your GitHub pages URL

# Author information
author:
  name: "Ghaly"
  email: "zhafrang638@gmail.com"

# Build settings
markdown: kramdown
theme: minima # You can change this to any other theme you prefer
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Social media links (optional)
social:
  github: "https://github.com/cherzs"
  linkedin: "https://www.linkedin.com/in/muhammad-zhafran-ghaly-383940214/"
  twitter: "https://twitter.com/your_twitter_handle"

# Navigation links (optional)
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"
  
# Other settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site

# Permalinks
permalink: pretty

# Custom variables (optional)
custom_var:
  example: "value"

# Other settings can be customized as needed
